nameOverride: "langgraph-react-agent"

env:
  MODEL_ID: ""
  BASE_URL: ""

auth:
  enabled: false
  audience: "langgraph-react-agent"
  allowedServiceAccounts: []
  createAuthDelegatorBinding: true

affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - ocp-j8fns-worker-cpu-3-94p9f
