controller:
  enabled: true
gateway:
  publicHost: mcp-gateway.apps.cluster-lk2p7.lk2p7.sandbox155.opentlc.com
mcpGatewayExtension:
  create: true
  gatewayRef:
    name: mcp-demo-gateway
    namespace: openshift-ingress